/** Adapter-bounded Go observations with host-owned expectations and verdicts. */
import type {TestDetail} from '@zxbench/types';
import {runInContainer,type ContainerRunOptions} from './containerRunner.js';
import {validObservationJson} from './quickJsObservation.js';
import {validJsonValuePredicate,matchesJsonValuePredicate,type JsonValuePredicate} from './jsonValuePredicate.js';
import type {JsonValue} from './isolatedJson.js';
import {splitGoSubmission} from './goSubmission.js';
export type GoJsonAdapter='goroutine-print'|'copy-prefix-alias'|'error-wrap'|'atoi-result'|'race-counter'|'fan-in'|'first-http';
export interface IsolatedGoJsonCase{id:string;calls:JsonValue[][];expected:JsonValuePredicate[]}
export interface IsolatedGoJsonContract{protocol:'isolated-go-json-v1'|'isolated-go-json-v2';entrypoint:string;adapter:GoJsonAdapter;cases:IsolatedGoJsonCase[]}
export const GO_JSON_IMAGE='zxbench/go@sha256:bbe499b0985c0481a47548381d03e2a46ded78e13411b8e5865b0efbdb391e03';
const rec=(v:unknown):v is Record<string,any>=>v!==null&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
const int=(v:unknown,min=-1e6,max=1e6)=>Number.isInteger(v)&&Number(v)>=min&&Number(v)<=max;
function validCall(a:GoJsonAdapter,x:unknown[]){if(a==='goroutine-print')return x.length===1&&int(x[0],0,1000);
 if(a==='copy-prefix-alias')return x.length===4&&Array.isArray(x[0])&&x[0].length<=1000&&x[0].every(v=>int(v))&&int(x[1],0,x[0].length)&&['independent','length'].includes(x[2] as string)&&int(x[3]);
 if(a==='error-wrap')return x.length===1&&typeof x[0]==='string'&&x[0].length<=128;
 if(a==='atoi-result')return x.length===2&&typeof x[0]==='string'&&x[0].length<=128&&['value','hasError'].includes(x[1] as string);
 if(a==='race-counter')return x.length===2&&int(x[0],1,2000)&&int(x[1],1,1000);
 if(a==='fan-in')return x.length===4&&int(x[0],0,64)&&int(x[1],0,2048)&&typeof x[2]==='boolean'&&['values','stats'].includes(x[3] as string);
 return a==='first-http'&&x.length===4&&['fastest','leak','allfail','canceled'].includes(x[0] as string)&&int(x[1],1,200)&&int(x[2],0,500)&&int(x[3],0,500);}
export function validIsolatedGoJsonContract(v:unknown):v is IsolatedGoJsonContract{const advanced=['race-counter','fan-in','first-http'];if(!rec(v)||!['isolated-go-json-v1','isolated-go-json-v2'].includes(v.protocol)||!['goroutine-print','copy-prefix-alias','error-wrap','atoi-result',...advanced].includes(v.adapter)||((v.protocol==='isolated-go-json-v2')!==advanced.includes(v.adapter))||typeof v.entrypoint!=='string'||!/^[A-Za-z_][A-Za-z0-9_.]*$/.test(v.entrypoint)||!Array.isArray(v.cases)||!v.cases.length||v.cases.length>100)return false;const ids=new Set<string>();return v.cases.every((c:unknown)=>rec(c)&&typeof c.id==='string'&&!ids.has(c.id)&&ids.add(c.id)&&Array.isArray(c.calls)&&c.calls.length>0&&c.calls.length<=100&&c.calls.every((x:unknown)=>Array.isArray(x)&&validObservationJson(x)&&validCall(v.adapter,x))&&Array.isArray(c.expected)&&c.expected.length===c.calls.length&&validObservationJson(c.expected)&&c.expected.every(validJsonValuePredicate));}
const q=(s:string)=>JSON.stringify(s),ints=(a:number[])=>`[]int{${a.join(',')}}`;
function call(a:GoJsonAdapter,e:string,x:JsonValue[],i:number){if(a==='goroutine-print')return `ch${i}:=make(chan int,${x[0]});${e}(${x[0]},ch${i});v${i}:=[]int{};for n:=range ch${i}{v${i}=append(v${i},n)};sort.Ints(v${i});add(v${i})`;
 if(a==='copy-prefix-alias'){const [v,n,action,value]=x as [number[],number,string,number];return `o${i}:=${ints(v)};c${i}:=${e}(o${i},${n});${action==='independent'&&n>0?`c${i}[0]=${value};add(o${i}[0]==${v[0]})`:`add(len(c${i}))`}`;}
 if(a==='error-wrap')return `add(errors.Is(${e}(${q(x[0] as string)}),ErrNotFound))`;
 if(a==='atoi-result')return x[1]==='value'?`v${i},_ := ${e}(${q(x[0] as string)});add(v${i})`:`_,er${i}:=${e}(${q(x[0] as string)});add(er${i}!=nil)`;
 if(a==='race-counter')return `c${i}:=&Counter{};start${i}:=make(chan struct{});var wg${i} sync.WaitGroup;for j:=0;j<${x[0]};j++{wg${i}.Add(1);go func(){defer wg${i}.Done();<-start${i};for k:=0;k<${x[1]};k++{c${i}.Inc()}}()};close(start${i});wg${i}.Wait();add(c${i}.Get())`;
 if(a==='fan-in')return `add(runFanIn(${x[0]},${x[1]},${x[2]},${q(x[3] as string)}))`;
 return `add(runFirst(${q(x[0] as string)},${x[1]},${x[2]},${x[3]}))`;}
function source(code:string,c:IsolatedGoJsonContract,calls:JsonValue[][]){let helper=c.adapter==='error-wrap'?`func fetch(id string) error {if id=="missing" {return ErrNotFound};return nil}`:'';
 if(c.adapter==='fan-in')helper=`func runFanIn(n,per int,withNil bool,mode string)any{chs:=make([]<-chan int,0,n+1);if withNil{chs=append(chs,nil)};for i:=0;i<n;i++{ch:=make(chan int);chs=append(chs,ch);go func(c chan int,base int){for j:=0;j<per;j++{c<-base+j};close(c)}(ch,i*per)};got:=[]int{};for v:=range FanIn(chs){got=append(got,v)};sort.Ints(got);if mode=="values"{return got};seen:=map[int]bool{};sum:=int64(0);for _,v:=range got{seen[v]=true;sum+=int64(v)};return []any{len(got),len(seen),sum}}`;
 if(c.adapter==='first-http')helper=`func testServer(delay int,body string)*httptest.Server{return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){time.Sleep(time.Duration(delay)*time.Millisecond);_,_=io.WriteString(w,body)}))}\nfunc runFirst(action string,it,d1,d2 int)any{if action=="allfail"{done:=make(chan string,1);go func(){done<-First(context.Background(),"http://127.0.0.1:1")}();select{case v:=<-done:return v;case<-time.After(2*time.Second):return "TIMEOUT"}};if action=="canceled"{ctx,cancel:=context.WithCancel(context.Background());cancel();start:=time.Now();v:=First(ctx,"http://127.0.0.1:1");return []any{v,time.Since(start)<time.Second}};a:=testServer(d1,"slow");defer a.Close();b:=testServer(d2,"fast");defer b.Close();if action=="fastest"{return First(context.Background(),a.URL,b.URL)};First(context.Background(),a.URL);time.Sleep(100*time.Millisecond);base:=runtime.NumGoroutine();for i:=0;i<it;i++{if First(context.Background(),b.URL,b.URL)!="fast"{return false}};time.Sleep(500*time.Millisecond);return runtime.NumGoroutine()<=base+15}`;
 const httpImports=c.adapter==='first-http'?`;"context";"io";"net/http";"net/http/httptest";"runtime";"time"`:'';
 const httpRefs=c.adapter==='first-http'?`\nvar _=context.Background\nvar _=io.ReadAll\nvar _=http.Get\nvar _=httptest.NewServer\nvar _=runtime.NumGoroutine\nvar _=time.Sleep`:'';
 const submitted=splitGoSubmission(code),imports=[...new Set(['"encoding/json"','"os"','"sort"','"sync"','"errors"','"fmt"',...httpImports.split(';').filter(Boolean),...submitted.imports])];
 return `package main\nimport(${imports.join(';')})\nvar _=sync.NewCond\nvar _=fmt.Errorf\nvar _=errors.New\nvar _=sort.Ints${httpRefs}\n${submitted.body}\n${helper}\nfunc main(){out:=[]any{};add:=func(v any){out=append(out,v)};${calls.map((x,i)=>call(c.adapter,c.entrypoint,x,i)).join(';')};json.NewEncoder(os.Stdout).Encode(out)}`;}
export function isolatedGoOptions(code:string,c:IsolatedGoJsonContract,calls:JsonValue[][],compileOnly=false):ContainerRunOptions{if(!validIsolatedGoJsonContract({...c,cases:[{id:'input',calls,expected:calls.map(()=>({equals:null}))}]}))throw Error('Invalid Go observation input');const race=c.protocol==='isolated-go-json-v2',timeout=c.adapter==='fan-in'?12000:c.adapter==='first-http'?30000:race?30000:10000;return{image:GO_JSON_IMAGE,command:['sh','-c',compileOnly?`go build ${race?'-race ':''}-o /tmp/app main.go`:`go run ${race?'-race ':''}main.go`],files:[{path:'main.go',content:source(code,c,calls)}],localImageOnly:true,readOnlyRoot:true,tmpfsSizeMb:race?256:128,tmpfsExec:true,readOnly:true,networkDisabled:true,runAsNonRoot:true,memoryMb:race?512:384,cpuLimit:1,pidsLimit:race?256:96,timeoutMs:timeout,maxOutputBytes:65536,env:{HOME:'/tmp',TMPDIR:'/tmp',GOCACHE:'/tmp/go-build',GOPATH:'/tmp/gopath',GOMAXPROCS:'1'}};}
export async function runIsolatedGoJsonSuite(code:string,c:IsolatedGoJsonContract){if(!validIsolatedGoJsonContract(c))throw Error('Invalid Go observation contract');const syntax=await runInContainer(isolatedGoOptions(code,c,c.cases[0].calls,true));let infrastructureError=syntax.infrastructureError;const details:TestDetail[]=[];for(const k of c.cases){if(infrastructureError)break;const startedAt=new Date().toISOString(),r=syntax.success?await runInContainer(isolatedGoOptions(code,c,k.calls)):syntax;infrastructureError=r.infrastructureError;let passed=false;if(r.success&&!r.timedOut&&!r.outputLimitExceeded&&!r.infrastructureError)try{const v:unknown=JSON.parse(r.stdout);passed=Array.isArray(v)&&v.length===k.expected.length&&validObservationJson(v)&&k.expected.every((p,i)=>matchesJsonValuePredicate(v[i],p));}catch{}details.push({testId:k.id,testType:'hidden',passed,stdout:r.stdout,stderr:r.stderr,actualOutput:r.stdout,exitCode:r.exitCode,timedOut:r.timedOut,duration:r.durationMs,startedAt,finishedAt:new Date().toISOString()});}return{compiled:syntax.success,compileError:syntax.success?undefined:syntax.stderr,infrastructureError,details,total:c.cases.length,passed:details.filter(x=>x.passed).length};}
